Repository thoth-station/slo-reporter, pull requests merged in 2020-09, with the labels that each got.

#84 Automatic update of dependency prometheus-api-client from 0.4.0 to 0.4.1
  Pipfile.lock
Labels: approved, bot

#85 Automatic update of dependency thoth-storages from 0.25.5 to 0.25.7
  Pipfile.lock
Labels: approved, bot, size/L

#86 Automatic update of dependency pandas from 1.1.1 to 1.1.2
  Pipfile.lock
Labels: approved, bot, size/L

#83 Update reference dashboard
  .env.template
  thoth/slo_reporter/configuration.py
  thoth/slo_reporter/sli_kebechet.py
  thoth/slo_reporter/sli_knowledge_graph.py
  thoth/slo_reporter/sli_learning.py
  thoth/slo_reporter/sli_pypi_knowledge_graph.py
  thoth/slo_reporter/sli_references.py
  thoth/slo_reporter/sli_workflow_latency.py
  thoth/slo_reporter/sli_workflow_quality.py
Labels: approved, size/M

#88 Release of version 0.5.5
  CHANGELOG.md
  thoth/slo_reporter/__init__.py
Labels: approved, bot, size/S

#89 Automatic update of dependency thoth-storages from 0.25.7 to 0.25.9
  Pipfile.lock
Labels: approved, bot

#92 Update evaluation method
  thoth/slo_reporter/sli_learning.py
Labels: approved, size/XS

#94 Automatic update of dependency thoth-storages from 0.25.9 to 0.25.10
  Pipfile.lock
Labels: approved, bot, size/M

#95 Automatic update of dependency thoth-storages from 0.25.9 to 0.25.10
  Pipfile.lock
Labels: approved, bot, size/M

#96 Release of version 0.5.6
  CHANGELOG.md
  thoth/slo_reporter/__init__.py
Labels: approved, bot, size/S

#98 Automatic update of dependency thoth-storages from 0.25.10 to 0.25.11
  Pipfile.lock
Labels: approved, bot, size/S

#97 Add thoth integrations and introduce generalization for files stored in Ceph
  Pipfile
  Pipfile.lock
  app.py
  thoth/slo_reporter/__init__.py
  thoth/slo_reporter/configuration.py
  thoth/slo_reporter/sli_base.py
  thoth/slo_reporter/sli_kebechet.py
  thoth/slo_reporter/sli_knowledge_graph.py
  thoth/slo_reporter/sli_learning.py
  thoth/slo_reporter/sli_pypi_knowledge_graph.py
  thoth/slo_reporter/sli_references.py
  thoth/slo_reporter/sli_report.py
  thoth/slo_reporter/sli_template.py
  thoth/slo_reporter/sli_thoth_integration.py
  thoth/slo_reporter/sli_user_api.py
  thoth/slo_reporter/sli_workflow_latency.py
  thoth/slo_reporter/sli_workflow_quality.py
  thoth/slo_reporter/static/templates/thoth_integrations.html
Labels: approved, size/XL

#99 Explain metrics and SLI, add Images on SLI
  README.md
  app.py
  thoth/slo_reporter/configuration.py
  thoth/slo_reporter/sli_apis/README.md
  thoth/slo_reporter/sli_apis/SLIUserAPI.png
  thoth/slo_reporter/sli_apis/__init__.py
  thoth/slo_reporter/sli_apis/sli_user_api.py
  thoth/slo_reporter/sli_backends/README.md
  thoth/slo_reporter/sli_backends/__init__.py
  thoth/slo_reporter/sli_backends/sli_workflow_latency.py
  thoth/slo_reporter/sli_backends/sli_workflow_quality.py
  thoth/slo_reporter/sli_knowledge_graph/README.md
  thoth/slo_reporter/sli_knowledge_graph/SLIKnowledgeGraph.png
  thoth/slo_reporter/sli_knowledge_graph/SLIKnowledgeGraphChanges.png
  thoth/slo_reporter/sli_knowledge_graph/__init__.py
  thoth/slo_reporter/sli_knowledge_graph/sli_knowledge_graph.py
  thoth/slo_reporter/sli_learning/README.md
  thoth/slo_reporter/sli_learning/SLILearning.png
  thoth/slo_reporter/sli_learning/SLILearningNewSolvers.png
  thoth/slo_reporter/sli_learning/SLILearningSolvedPackages.png
  thoth/slo_reporter/sli_learning/__init__.py
  thoth/slo_reporter/sli_learning/sli_learning.py
  thoth/slo_reporter/sli_python_knowledge_graph/README.md
  thoth/slo_reporter/sli_python_knowledge_graph/SLIPyPIKnowledgeGraph.png
  thoth/slo_reporter/sli_python_knowledge_graph/SLIPyPIKnowledgeGraphChanges.png
  thoth/slo_reporter/sli_python_knowledge_graph/__init__.py
  thoth/slo_reporter/sli_python_knowledge_graph/sli_pypi_knowledge_graph.py
  thoth/slo_reporter/sli_report.py
  thoth/slo_reporter/sli_thoth_integrations/README.md
  thoth/slo_reporter/sli_thoth_integrations/SLIThothIntegrations.png
  thoth/slo_reporter/sli_thoth_integrations/__init__.py
  thoth/slo_reporter/sli_thoth_integrations/sli_thoth_integration.py
  thoth/slo_reporter/sli_thoth_services/README.md
  thoth/slo_reporter/sli_thoth_services/SLIKebechet.png
  thoth/slo_reporter/sli_thoth_services/SLIKebechetChanges.png
  thoth/slo_reporter/sli_thoth_services/__init__.py
  thoth/slo_reporter/sli_thoth_services/sli_kebechet.py
  thoth/slo_reporter/static/templates/thoth_kebechet.html
Labels: approved, size/XL

#100 Adjust links to READMEs and images
  README.md
  thoth/slo_reporter/sli_apis/README.md
  thoth/slo_reporter/sli_knowledge_graph/README.md
  thoth/slo_reporter/sli_learning/README.md
  thoth/slo_reporter/sli_python_knowledge_graph/README.md
  thoth/slo_reporter/sli_thoth_integrations/README.md
  thoth/slo_reporter/sli_thoth_services/README.md
Labels: approved, size/M

#101 remove duplicate .png from link
  thoth/slo_reporter/sli_knowledge_graph/README.md
Labels: approved, size/XS

#102 Add SLI for Security-Indicator
  thoth/slo_reporter/sli_learning/README.md
  thoth/slo_reporter/sli_learning/sli_learning.py
Labels: approved, size/S

#104 Automatic update of dependency thoth-common from 0.19.0 to 0.20.0
  Pipfile.lock
Labels: approved, bot, size/L

#107 Automatic update of dependency hypothesis from 5.35.4 to 5.36.0
  Pipfile.lock
Labels: approved, bot, size/L

#109 Release of version 0.5.7
  CHANGELOG.md
  thoth/slo_reporter/__init__.py
Labels: approved, bot, size/S

#112 Automatic update of dependency pytest from 6.0.2 to 6.1.0
  Pipfile.lock
Labels: approved, bot, size/M

#113 Automatic update of dependency hypothesis from 5.36.0 to 5.36.1
  Pipfile.lock
Labels: approved, bot, size/M

#116 Add quality latency sli
  .env.template
  thoth/slo_reporter/configuration.py
  thoth/slo_reporter/sli_backends/README.md
  thoth/slo_reporter/sli_backends/SLIWorkflowLatency.png
  thoth/slo_reporter/sli_backends/SLIWorkflowQuality.png
  thoth/slo_reporter/sli_backends/SLIWorkflowTaskQuality.png
  thoth/slo_reporter/sli_backends/__init__.py
  thoth/slo_reporter/sli_backends/sli_workflow_latency.py
  thoth/slo_reporter/sli_backends/sli_workflow_task_quality.py
  thoth/slo_reporter/sli_knowledge_graph/sli_knowledge_graph.py
  thoth/slo_reporter/sli_learning/sli_learning.py
  thoth/slo_reporter/sli_references.py
  thoth/slo_reporter/sli_report.py
  thoth/slo_reporter/sli_template.py
  thoth/slo_reporter/static/templates/thoth_service_latency.html
  thoth/slo_reporter/static/templates/thoth_workflow_latency.html
  thoth/slo_reporter/static/templates/thoth_workflow_quality.html
  thoth/slo_reporter/static/templates/thoth_workflow_task_quality.html
Labels: approved, size/L

#118 Automatic update of dependency thoth-storages from 0.25.11 to 0.25.12
  Pipfile.lock
Labels: approved, bot, size/S

#119 Release of version 0.5.8
  CHANGELOG.md
  thoth/slo_reporter/__init__.py
Labels: approved, bot, size/S

#120 Automatic update of dependency thoth-storages from 0.25.12 to 0.25.13
  Pipfile.lock
Labels: approved, bot, size/XS
