Repository thoth-station/slo-reporter, pull requests merged in 2020-10, with the labels that each got.

#123 Automatic update of dependency thoth-storages from 0.25.13 to 0.25.14
  Pipfile.lock
Labels: approved, bot, size/M

#124 Automatic update of dependency thoth-storages from 0.25.14 to 0.25.15
  Pipfile.lock
Labels: approved, bot

#125 Automatic update of dependency pytest from 6.1.0 to 6.1.1
  Pipfile.lock
Labels: approved, bot, size/M

#126 Automatic update of dependency hypothesis from 5.36.1 to 5.37.0
  Pipfile.lock
Labels: approved, bot, size/M

#131 Add sli columns check
  app.py
  thoth/slo_reporter/sli_apis/sli_user_api.py
  thoth/slo_reporter/sli_backends/sli_workflow_latency.py
  thoth/slo_reporter/sli_backends/sli_workflow_quality.py
  thoth/slo_reporter/sli_backends/sli_workflow_task_quality.py
  thoth/slo_reporter/sli_base.py
  thoth/slo_reporter/sli_knowledge_graph/sli_knowledge_graph.py
  thoth/slo_reporter/sli_learning/sli_learning.py
  thoth/slo_reporter/sli_python_knowledge_graph/sli_pypi_knowledge_graph.py
  thoth/slo_reporter/sli_report.py
  thoth/slo_reporter/sli_thoth_integrations/sli_thoth_integration.py
  thoth/slo_reporter/sli_thoth_services/sli_kebechet.py
Labels: approved, size/M

#132 reset time to utcnow
  app.py
Labels: approved, size/XS

#133 Automatic update of dependency pandas from 1.1.2 to 1.1.3
  Pipfile.lock
Labels: approved, bot, size/L

#134 Automatic update of dependency thoth-common from 0.20.0 to 0.20.1
  Pipfile.lock
Labels: approved, bot

#135 Automatic update of dependency hypothesis from 5.37.0 to 5.37.1
  Pipfile.lock
Labels: approved, bot

#130 Add ‚change since last week‘ metrics
  app.py
  thoth/slo_reporter/configuration.py
  thoth/slo_reporter/sli_apis/sli_user_api.py
  thoth/slo_reporter/sli_knowledge_graph/sli_knowledge_graph.py
  thoth/slo_reporter/sli_learning/sli_learning.py
  thoth/slo_reporter/sli_python_knowledge_graph/sli_pypi_knowledge_graph.py
  thoth/slo_reporter/sli_thoth_services/sli_kebechet.py
  thoth/slo_reporter/static/templates/pypi_knowledge_graph.html
  thoth/slo_reporter/static/templates/thoth_kebechet.html
  thoth/slo_reporter/static/templates/thoth_knowledge_graph.html
  thoth/slo_reporter/static/templates/thoth_learning.html
  thoth/slo_reporter/static/templates/thoth_user_api.html
  thoth/slo_reporter/utils.py
Labels: approved, size/L

#140 Automatic update of dependency hypothesis from 5.37.1 to 5.37.3
  Pipfile.lock
Labels: approved, bot, size/M

#142 Release of version 0.5.9
  CHANGELOG.md
  thoth/slo_reporter/__init__.py
Labels: approved, bot, size/S

#144 Adjust description
  thoth/slo_reporter/sli_thoth_services/sli_kebechet.py
Labels: approved, size/XS

#145 check for DRY_RUN
  thoth/slo_reporter/sli_apis/sli_user_api.py
  thoth/slo_reporter/sli_knowledge_graph/sli_knowledge_graph.py
  thoth/slo_reporter/sli_learning/sli_learning.py
  thoth/slo_reporter/sli_python_knowledge_graph/sli_pypi_knowledge_graph.py
  thoth/slo_reporter/sli_thoth_services/sli_kebechet.py
Labels: approved, size/L

#147 Automatic update of dependency thoth-common from 0.20.1 to 0.20.2
  Pipfile.lock
Labels: approved, bot, size/L

#148 Automatic update of dependency thoth-common from 0.20.1 to 0.20.2
  Pipfile.lock
Labels: approved, bot, size/L

#149 Automatic update of dependency hypothesis from 5.37.3 to 5.37.4
  Pipfile.lock
Labels: approved, bot, size/L

#150 Release of version 0.6.0
  CHANGELOG.md
  thoth/slo_reporter/__init__.py
Labels: approved, bot, size/S

#154 Add environment to email title to avoid confusion
  thoth/slo_reporter/sli_report.py
Labels: approved, size/XS

#156 Release of version 0.6.1
  CHANGELOG.md
  thoth/slo_reporter/__init__.py
Labels: approved, bot, size/XS
