Repository thoth-station/slo-reporter, pull requests merged in 2020-06, with the labels that each got.

#25 Add apiVersion
  README.md
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/S

#27 Release of version 0.2.1
  CHANGELOG.md
  thoth/slo_reporter/__init__.py
Labels: bot, size/S

#28 Merge pull request #27 from thoth-station/v0.2.1
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
  thoth/slo_reporter/sli_kebechet.py
Labels: approved, size/S

#33 Automatic update of dependency prometheus-api-client from 0.2.0 to 0.3.1
  Pipfile.lock
Labels: bot, size/XS

#30 Add Thoth reports references
  README.md
  thoth/slo_reporter/configuration.py
  thoth/slo_reporter/sli_kebechet.py
  thoth/slo_reporter/sli_references.py
  thoth/slo_reporter/static/templates/thoth_kebechet.html
  thoth/slo_reporter/static/templates/thoth_references.html
Labels: approved, size/M

#31 Modify query workflows
  app.py
  openshift/cronJob-template.yaml
  thoth/slo_reporter/configuration.py
  thoth/slo_reporter/sli_kebechet.py
  thoth/slo_reporter/sli_knowledge_graph.py
  thoth/slo_reporter/sli_learning.py
  thoth/slo_reporter/sli_pypi_knowledge_graph.py
  thoth/slo_reporter/sli_user_api.py
  thoth/slo_reporter/sli_workflow_quality.py
Labels: approved, size/L

#35 Release of version 0.3.0
  CHANGELOG.md
  thoth/slo_reporter/__init__.py
Labels: bot, size/S

#36 relock
  Pipfile.lock
  thoth/slo_reporter/sli_workflow_quality.py
Labels: approved, size/L

#38 Release of version 0.3.1
  CHANGELOG.md
  thoth/slo_reporter/__init__.py
Labels: bot, size/XS

#41 Generalize workflows SLI/SLO for quality and latency
  .env.template
  README.md
  app.py
  openshift/buildConfig-template.yaml
  thoth/slo_reporter/configuration.py
  thoth/slo_reporter/sli_kebechet.py
  thoth/slo_reporter/sli_knowledge_graph.py
  thoth/slo_reporter/sli_learning.py
  thoth/slo_reporter/sli_pypi_knowledge_graph.py
  thoth/slo_reporter/sli_report.py
  thoth/slo_reporter/sli_template.py
  thoth/slo_reporter/sli_user_api.py
  thoth/slo_reporter/sli_workflow_latency.py
  thoth/slo_reporter/sli_workflow_quality.py
  thoth/slo_reporter/static/templates/thoth_service_latency.html
  thoth/slo_reporter/static/templates/thoth_service_quality.html
Labels: approved

#43 Release of version 0.4.0
  CHANGELOG.md
  thoth/slo_reporter/__init__.py
Labels: bot

#44 Change time
  openshift/cronJob-template.yaml
Labels: approved

#48 Feature/store sli
  .env.template
  OWNERS
  Pipfile
  Pipfile.lock
  app.py
  openshift/cronJob-template.yaml
  thoth/slo_reporter/__init__.py
  thoth/slo_reporter/configuration.py
  thoth/slo_reporter/sli_report.py
  thoth/slo_reporter/utils.py
Labels: approved, size/XXL
