Repository thoth-station/slo-reporter, pull requests merged in 2020-11, with the labels that each got.

#162 port to python 38
  .aicoe-ci.yaml
  .thoth.yaml
  Pipfile.lock
Labels: approved, size/XL

#163 Add check for Thanos availability before starting to acquire metrics.
  app.py
Labels: approved, size/M

#164 Adjust metrics due to changes on Prometheus side
  thoth/slo_reporter/sli_apis/sli_user_api.py
  thoth/slo_reporter/sli_knowledge_graph/sli_knowledge_graph.py
  thoth/slo_reporter/sli_learning/sli_learning.py
  thoth/slo_reporter/sli_python_knowledge_graph/sli_pypi_knowledge_graph.py
  thoth/slo_reporter/sli_thoth_services/sli_kebechet.py
Labels: approved, size/S

#167 Updated Pipfile with python38
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
  .zuul.yaml
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#168 update .aicoe.yaml
  .aicoe-ci.yaml
Labels: size/XS
