Repository thoth-station/slo-reporter, pull requests merged in 2020-07, with the labels that each got.

#49 Feature/standardize
  README.md
  app.py
  thoth/slo_reporter/configuration.py
  thoth/slo_reporter/sli_base.py
  thoth/slo_reporter/sli_kebechet.py
  thoth/slo_reporter/sli_knowledge_graph.py
  thoth/slo_reporter/sli_learning.py
  thoth/slo_reporter/sli_pypi_knowledge_graph.py
  thoth/slo_reporter/sli_user_api.py
  thoth/slo_reporter/sli_workflow_latency.py
  thoth/slo_reporter/sli_workflow_quality.py
  thoth/slo_reporter/static/templates/pypi_knowledge_graph.html
  thoth/slo_reporter/static/templates/thoth_kebechet.html
  thoth/slo_reporter/static/templates/thoth_knowledge_graph.html
  thoth/slo_reporter/static/templates/thoth_learning.html
  thoth/slo_reporter/static/templates/thoth_user_api.html
Labels: approved, size/L

#50 Feature/run multiple times
  .env.template
  app.py
  thoth/slo_reporter/configuration.py
  thoth/slo_reporter/sli_kebechet.py
  thoth/slo_reporter/sli_knowledge_graph.py
  thoth/slo_reporter/sli_learning.py
  thoth/slo_reporter/sli_pypi_knowledge_graph.py
  thoth/slo_reporter/sli_references.py
  thoth/slo_reporter/sli_report.py
  thoth/slo_reporter/sli_user_api.py
  thoth/slo_reporter/sli_workflow_latency.py
  thoth/slo_reporter/sli_workflow_quality.py
  thoth/slo_reporter/utils.py
Labels: size/XL

#52 Release of version 0.5.0
  CHANGELOG.md
  thoth/slo_reporter/__init__.py
Labels: approved, bot, size/M

#55 Release of version 0.5.1
  CHANGELOG.md
  thoth/slo_reporter/__init__.py
Labels: approved, bot, size/XS

#56 Add day of week check to send emails
  app.py
  thoth/slo_reporter/configuration.py
Labels: approved, size/S

#58 Release of version 0.5.2
  CHANGELOG.md
  thoth/slo_reporter/__init__.py
Labels: approved, bot, size/XS

#59 Adjust User-API SLI retrieve
  thoth/slo_reporter/sli_user_api.py
  thoth/slo_reporter/sli_workflow_latency.py
  thoth/slo_reporter/utils.py
Labels: approved, size/M

#60 Automatic update of dependency thoth-storages from 0.24.0 to 0.24.3
  Pipfile.lock
Labels: approved, bot, size/M

#62 Release of version 0.5.3
  CHANGELOG.md
  thoth/slo_reporter/__init__.py
Labels: approved, bot, size/XS

#63 Add SLI for security workflow
  thoth/slo_reporter/configuration.py
  thoth/slo_reporter/sli_learning.py
Labels: approved, size/S

#64 Automatic update of dependency prometheus-api-client from 0.3.1 to 0.4.0
  Pipfile.lock
Labels: approved, bot, size/L

#65 Automatic update of dependency thoth-storages from 0.24.3 to 0.24.5
  Pipfile.lock
Labels: approved, bot, size/L

#67 Automatic update of dependency pandas from 1.0.5 to 1.1.0
  Pipfile.lock
Labels: approved, bot
