Repository thoth-station/slo-reporter, pull requests merged in 2020-05, with the labels that each got.

#1 SLO reporter
  .github/CODEOWNERS
  Pipfile
  Pipfile.lock
  README.md
  app.py
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
  template/__init__.py
  thoth/slo_reporter/__init__.py
  thoth/slo_reporter/sli_metrics.py
  thoth/slo_reporter/sli_report.py
Labels: approved, do-not-merge/needs-rebase, size/XL

#5 Use thanos secret
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#4 Add environment to distinguish metrics
  app.py
  thoth/slo_reporter/sli_report.py
Labels: approved, size/XS

#6 New SLI and refactorting for scalability
  Pipfile
  Pipfile.lock
  README.md
  app.py
  openshift/cronJob-template.yaml
  thoth/slo_reporter/__init__.py
  thoth/slo_reporter/sli_base.py
  thoth/slo_reporter/sli_knowledge_graph.py
  thoth/slo_reporter/sli_learning.py
  thoth/slo_reporter/sli_metrics.py
  thoth/slo_reporter/sli_pypi_knowledge_graph.py
  thoth/slo_reporter/sli_references.py
  thoth/slo_reporter/sli_report.py
  thoth/slo_reporter/sli_template.py
  thoth/slo_reporter/sli_user_api.py
  thoth/slo_reporter/sli_workflow_quality.py
  thoth/slo_reporter/templates/base.html
  thoth/slo_reporter/templates/pypi_knowledge_graph.html
  thoth/slo_reporter/templates/thoth_knowledge_graph.html
  thoth/slo_reporter/templates/thoth_learning.html
  thoth/slo_reporter/templates/thoth_references.html
  thoth/slo_reporter/templates/thoth_service.html
  thoth/slo_reporter/templates/thoth_user_api.html
Labels: approved, size/XXL

#9 Add solver info and environment info
  thoth/slo_reporter/sli_learning.py
  thoth/slo_reporter/sli_report.py
Labels: size/S

#12 Fix Coala
  openshift/cronJob-template.yaml
  thoth/slo_reporter/sli_report.py
Labels: approved, size/XS

#13 Dry run
  Pipfile
  Pipfile.lock
  README.md
  app.py
  thoth/slo_reporter/configuration.py
  thoth/slo_reporter/sli_knowledge_graph.py
  thoth/slo_reporter/sli_learning.py
  thoth/slo_reporter/sli_pypi_knowledge_graph.py
  thoth/slo_reporter/sli_references.py
  thoth/slo_reporter/sli_report.py
  thoth/slo_reporter/sli_user_api.py
  thoth/slo_reporter/sli_workflow_quality.py
  thoth/slo_reporter/templates/base.html
  thoth/slo_reporter/templates/pypi_knowledge_graph.html
  thoth/slo_reporter/templates/thoth_knowledge_graph.html
  thoth/slo_reporter/templates/thoth_learning.html
  thoth/slo_reporter/templates/thoth_references.html
  thoth/slo_reporter/templates/thoth_service.html
  thoth/slo_reporter/templates/thoth_user_api.html
Labels: do-not-merge/needs-rebase, size/L

#14 Configuration and style
  app.py
  openshift/cronJob-template.yaml
  thoth/slo_reporter/SLO-reporter.html
  thoth/slo_reporter/configuration.py
  thoth/slo_reporter/sli_knowledge_graph.py
  thoth/slo_reporter/sli_learning.py
  thoth/slo_reporter/sli_pypi_knowledge_graph.py
  thoth/slo_reporter/sli_references.py
  thoth/slo_reporter/sli_report.py
  thoth/slo_reporter/sli_template.py
  thoth/slo_reporter/sli_user_api.py
  thoth/slo_reporter/sli_workflow_quality.py
  thoth/slo_reporter/static/templates/base.html
  thoth/slo_reporter/static/templates/end.html
  thoth/slo_reporter/static/templates/intro.html
  thoth/slo_reporter/static/templates/pypi_knowledge_graph.html
  thoth/slo_reporter/static/templates/start.html
  thoth/slo_reporter/static/templates/style.html
  thoth/slo_reporter/static/templates/thoth_knowledge_graph.html
  thoth/slo_reporter/static/templates/thoth_learning.html
  thoth/slo_reporter/static/templates/thoth_references.html
  thoth/slo_reporter/static/templates/thoth_service.html
  thoth/slo_reporter/static/templates/thoth_user_api.html
  thoth/slo_reporter/templates/base.html
  thoth/slo_reporter/templates/pypi_knowledge_graph.html
  thoth/slo_reporter/templates/thoth_knowledge_graph.html
  thoth/slo_reporter/templates/thoth_learning.html
  thoth/slo_reporter/templates/thoth_references.html
  thoth/slo_reporter/templates/thoth_service.html
  thoth/slo_reporter/templates/thoth_user_api.html
Labels: approved, size/XL

#23 updated zuul config file
  .zuul.yaml
Labels: approved, size/XS

#22 Remove int
  app.py
  thoth/slo_reporter/sli_knowledge_graph.py
  thoth/slo_reporter/sli_learning.py
  thoth/slo_reporter/sli_pypi_knowledge_graph.py
Labels: approved, size/S

#19 pre commit changes
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
  .github/PULL_REQUEST_TEMPLATE.md
  .pre-commit-config.yaml
  app.py
  thoth/slo_reporter/SLO-reporter.html
  thoth/slo_reporter/sli_base.py
  thoth/slo_reporter/sli_knowledge_graph.py
  thoth/slo_reporter/sli_learning.py
  thoth/slo_reporter/sli_pypi_knowledge_graph.py
  thoth/slo_reporter/sli_report.py
  thoth/slo_reporter/sli_user_api.py
  thoth/slo_reporter/sli_workflow_quality.py
Labels: approved, enhancement, size/L

#18 Automatic update of dependency prometheus-client from 0.7.1 to 0.8.0
  Pipfile.lock
Labels: bot, size/M

#21 Add kebechet SLI report
  README.md
  thoth/slo_reporter/sli_kebechet.py
  thoth/slo_reporter/sli_report.py
  thoth/slo_reporter/sli_template.py
  thoth/slo_reporter/static/templates/thoth_kebechet.html
Labels: approved, size/L

#17 Release of version 0.2.0
  CHANGELOG.md
  thoth/slo_reporter/__init__.py
Labels: bot, size/M
