Repository thoth-station/slo-reporter, pull requests merged in 2020-08, with the labels that each got.

#70 Modify environment variable
  .env.template
  thoth/slo_reporter/configuration.py
Labels: approved, size/XS

#72 Automatic update of dependency thoth-storages from 0.24.5 to 0.25.5
  Pipfile.lock
Labels: approved, bot

#75 Release of version 0.5.4
  CHANGELOG.md
  thoth/slo_reporter/__init__.py
Labels: approved, bot

#74 Automatic update of dependency pandas from 1.1.0 to 1.1.1
  Pipfile.lock
Labels: approved, bot, do-not-merge/needs-rebase, size/M
