Repository thoth-station/slo-reporter, pull requests merged in 2021-03, with the labels that each got.

#215 :arrow_up: update CI/CD configuration
  .aicoe-ci.yaml
  .coafile
  .pre-commit-config.yaml
  .prow.yaml
Labels: approved, size/M

#214 Add build analysis in the report sent by email
  thoth/slo_reporter/configuration.py
Labels: approved, lgtm, size/XS

#220 Add integration per user SLI
  .env.template
  app.py
  thoth/slo_reporter/sli_learning/sli_learning.py
  thoth/slo_reporter/sli_report.py
  thoth/slo_reporter/sli_template.py
  thoth/slo_reporter/sli_thoth_integrations/README.md
  thoth/slo_reporter/sli_thoth_integrations/__init__.py
  thoth/slo_reporter/sli_thoth_integrations/sli_thoth_integration_users.py
  thoth/slo_reporter/static/templates/thoth_integrations_users.html
Labels: approved, size/L

#227 Fix key for changes since last week
  thoth/slo_reporter/sli_thoth_integrations/sli_thoth_integration_users.py
Labels: approved, size/XS

#233 Generalize references
  .env.template
  app.py
  thoth/slo_reporter/configuration.py
  thoth/slo_reporter/sli_references.py
Labels: approved, lgtm, size/M

#238 Add workflows tasks latency
  .gitignore
  app.py
  thoth/slo_reporter/sli_backends/__init__.py
  thoth/slo_reporter/sli_backends/sli_workflow_task_latency.py
  thoth/slo_reporter/sli_report.py
  thoth/slo_reporter/sli_template.py
  thoth/slo_reporter/static/templates/thoth_workflow_task_latency.html
Labels: approved, size/L
