Repository thoth-station/slo-reporter, pull requests merged in 2021-06, with the labels that each got.

#271 Add standard GitHub templates
  .github/ISSUE_TEMPLATE/kebechet_info.md
  .github/ISSUE_TEMPLATE/kebechet_update.md
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
Labels: size/S

#278 Add env label
  Pipfile
  Pipfile.lock
  app.py
  thoth/slo_reporter/configuration.py
Labels: approved, size/L

#283 Remove qeb-hwt bits
  README.md
  thoth/slo_reporter/configuration.py
  thoth/slo_reporter/sli_thoth_adviser_inputs/README.md
Labels: approved, lgtm, size/S
