Repository thoth-station/slo-reporter, pull requests merged in 2021-04, with the labels that each got.

#242 Add defaults
  thoth/slo_reporter/configuration.py
Labels: approved, size/S

#254 some minor wording changes
  .pre-commit-config.yaml
  OWNERS
  app.py
  thoth/slo_reporter/sli_references.py
  thoth/slo_reporter/sli_report.py
  thoth/slo_reporter/static/templates/thoth_base_images.html
  thoth/slo_reporter/static/templates/thoth_hardware.html
  thoth/slo_reporter/static/templates/thoth_recommendations.html
  thoth/slo_reporter/static/templates/thoth_solvers.html
Labels: approved, size/L

#255 Minor adjustments
  thoth/slo_reporter/sli_thoth_adviser_inputs/sli_thoth_hardware.py
  thoth/slo_reporter/static/templates/thoth_integrations.html
Labels: approved, size/XS
